---
title: "Instrumental Variables"
subtitle: "EC 421, Set 11"
author: "Edward Rubin"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, middle

```{R, setup, include = F}
# devtools::install_github("dill/emoGG")
library(pacman)
p_load(
  broom, here, tidyverse,
  emoGG, latex2exp, ggplot2, ggthemes, viridis, extrafont, gridExtra,
  wooldridge,
  kableExtra,
  data.table,
  dplyr,
  lubridate,
  magrittr, knitr, parallel
)
# Define pink color
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
purple <- "#6A5ACD"
# Dark slate grey: #314f4f
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F
)
opts_chunk$set(dev = "svg")
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
# A blank theme for ggplot
theme_empty <- theme_bw() + theme(
  line = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  plot.margin = structure(c(0, 0, -0.5, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_simple <- theme_bw() + theme(
  line = element_blank(),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text.x = element_text(size = 18, family = "STIXGeneral"),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  # plot.margin = structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_math <- theme_void() + theme(
  text = element_text(family = "MathJax_Math"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_serif <- theme_void() + theme(
  text = element_text(family = "MathJax_Main"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes <- theme_void() + theme(
  text = element_text(family = "Fira Sans Book"),
  axis.title = element_text(size = 18),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 20))
```

# Prologue

---
name: schedule

# Schedule

## Last Time

Causality

## Today

- Econ. Masters program
- Review: Causality
- New: Instrumental variables

## Upcoming

Assignment soon.
---
layout: false
name: masters

# Master's Program
## Applied Economics

You could be a master of (applied) economics...

- 1-year program including courses on applied econometrics, data science, and "big data".
- Awesome opportunity to focus on applying economic methods to real-world questions/scenarios.
- [Applications are due by **May 1 (2019)**](https://economics.uoregon.edu/masters/).

More information: [https://economics.uoregon.edu/masters/](https://economics.uoregon.edu/masters/)

---
layout: false
class: inverse, middle
# Causality
## Review
---
layout: true
# Causality
## Review
---
name: causality_review

In our last lecture, we returned to the concept of .hi[causality].

--

We worked through the *Rubin causal model*, in which we defined

- $\color{#e64173}{y_{1i}:}$ the outcome for individual $i$ if she had received treatment

--
- $\color{#6A5ACD}{y_{0i}:}$ the outcome for individual $i$ if she had not received treatment

--

and we referred to individuals who did not receive treatment as *control*.

--

***If*** we were able to know both $\color{#e64173}{y_{1i}}$ ***and*** $\color{#6A5ACD}{y_{0i}}$, we could calculate the causal effect of treatment for individual $i$, _i.e._,

--

$$
\begin{align}
  \tau_i = \color{#e64173}{y_{1i}} - \color{#6A5ACD}{y_{0i}}
\end{align}
$$

---

.hi-slate[Fundamental problem of causal inference:]
<br>We cannot simultaneously know $\color{#e64173}{y_{1i}}$ and $\color{#6A5ACD}{y_{0i}}$.

--

Either we observe individual $i$ in the treatment group, _i.e._,
$$
\begin{align}
  \tau_i = \color{#e64173}{y_{1i}} - \color{#6A5ACD}{?}
\end{align}
$$

--

or we observe $i$ in the control group, _i.e._,
$$
\begin{align}
  \tau_i = \color{#e64173}{?} - \color{#6A5ACD}{y_{0i}}
\end{align}
$$

--

but never both at the same time.
---

If we want to know $\tau_i$ (or at least $\overline{\tau}$), what can we do?

--

**Idea:** Estimate the .hi-slate[average treatment effect] as the difference between the average outcomes in the treatment group and the control group, _i.e._,

$$
\begin{align}
  \color{#e64173}{\mathop{Avg}\left( y_i\mid D_i = 1 \right)} - \color{#6A5ACD}{\mathop{Avg}\left( y_i\mid D_i =0 \right)}
\end{align}
$$
where $D_i=1$ if $i$ received treatment, and $D_i=0$ if $i$ is in the control group.

---

**Result:** We showed that even when the treatment effect is constant (meaning $\tau_i=\tau$ for all $i$),
$$
\begin{align}
  &\color{#e64173}{\mathop{Avg}\left( y_i\mid D_i = 1 \right)} - \color{#6A5ACD}{\mathop{Avg}\left( y_i\mid D_i =0 \right)} \\
  &\quad\quad = \tau + \underbrace{\color{#e64173}{\mathop{Avg}\left(\color{#6A5ACD}{y_{0,i}} \mid D_i = 1 \right)} - \color{#6A5ACD}{\mathop{Avg}\left( y_{0,i}\mid D_i =0 \right)}}_{\color{#FFA500}{\text{Selection bias}}}
\end{align}
$$

which says that the difference in the groups' means will give us a **biased estimate** for the causal effect of treatment .hi-orange[if we have selection bias.]
---

**Q:** What is this .hi-orange[selection bias]?

--

**A:** **(Informal)** We have selection bias when our control group doesn't offer a good comparison for our treatment group.

--

Specifically, the control group doesn't give us a good .hi-orange[counterfactual] for .orange[what our treatment group would have looked like if the members had not received treatment.]
--
 Basically, the groups are different.

--

**A:** **(Formal)** The .pink[average *untreated* outcome for a member of our **treatment group**] (which we cannot observe) differs from the .purple[average *untreated* outcome for a member of our **control group**], _i.e._,
$$
\begin{align}
  \color{#e64173}{\mathop{Avg}\left(\color{#6A5ACD}{y_{0,i}} \mid D_i = 1 \right)} - \color{#6A5ACD}{\mathop{Avg}\left( y_{0,i}\mid D_i =0 \right)}
\end{align}
$$
---

.hi-slate[Practical problem:] Selection bias is also difficult to observe

$$
\begin{align}
  \underbrace{\color{#e64173}{\mathop{Avg}\left(\color{#6A5ACD}{y_{0,i}} \mid D_i = 1 \right)}}_{\color{#e64173}{\text{Unobservable}}} - \color{#6A5ACD}{\mathop{Avg}\left( y_{0,i}\mid D_i =0 \right)}
\end{align}
$$

(back to the *fundamental problem of causal inference*)

--

.hi-slate[Bigger problem:] If selection bias is present, our estimate for $\tau$ is biased, preventing us from understanding the causal effect of treatment.

--

Sounds a bit like omitted-variable bias, right?
--
 Our .pink[treatment] variable is correlated with something that makese the two groups different.
---

**Example:** Imagine we have two people—Al and Bri—and a single binary treatment, college. We interested in the effect of college on earnings.

.pull-left[.center[
.pink[Earn.sub[1,Al]] = .pink[$60K]
<br>.purple[Earn.sub[0,Al]] = .purple[$30K]
]]
.pull-right[
.pink[Earn.sub[1,Bri]] = .pink[$140K]
<br>.purple[Earn.sub[0,Bri]] = .purple[$110K]
]

--

They both have the same treatment effect (return to college)
--
<br> $\quad\quad\tau$.sub[Al] = .pink[Earn.sub[1,Al]] - .purple[Earn.sub[0,Al]] = .pink[$60K] - .purple[$30K] = $30K
--
<br> $\quad\quad\tau$.sub[Bri] = .pink[Earn.sub[1,Bri]] - .purple[Earn.sub[0,Bri]] = .pink[$140K] - .purple[$100K] = $30K

--

but any real-world estimate would have serious selection issues since .purple[Earn.sub[0,Al]] ≠ .purple[Earn.sub[0,Bri].]
---
count: false

**Example:** Imagine we have two people—Al and Bri—and a single binary treatment, college. We interested in the effect of college on earnings.

.pull-left[.center[
.pink[Earn.sub[1,Al]] = .pink[$60K]
<br>.purple[Earn.sub[0,Al]] = .purple[$30K]
]]
.pull-right[
.pink[Earn.sub[1,Bri]] = .pink[$140K]
<br>.purple[Earn.sub[0,Bri]] = .purple[$110K]
]

The selection bias...

--

If Bri attended college (D.sub[Bri]=1) and Al did not (D.sub[Al]=0):
<br>
$\quad\quad\hat{\tau}$ = .pink[Earn.sub[1,Bri]] - .purple[Earn.sub[0,Al]] = .pink[$140K] - .purple[$30K] = $110K

--

If Al attended college (D.sub[Al]=1) and Bri did not (D.sub[Bri]=0):
<br>
$\quad\quad\hat{\tau}$ = .pink[Earn.sub[1,Al]] - .purple[Earn.sub[0,Bri]] = .pink[$60K] - .purple[$110K] = -$50K



---

We have (at least) two problems...

1. Selection bias is difficult to observe

2. If selection bias is present, our estimate for $\tau$ is biased, preventing us from understanding the causal effect of treatment.

--

.hi-slate[Solution:] Eliminate/minimize selection bias.

--

- .hi-slate[Option 1:] .hi-pink[Distribute treatment] in a way such that the treatment and control groups are essentially identical
--
 (experiments).

--

- .hi-slate[Option 2:] .hi-purple[Build a control] group that *matches* the treatment group
--
 <br>(life with observational data).
---
layout: true
# Instrumental variables
---
class: inverse, middle
---
name: intro

## Intro

.hi[Instrumental variables (IV)] is one route econometricians often take toward estimating the causal effect of a treatment/program.

--

*Recall:* .hi-orange[Selection bias] means our .pink[treatment] and .purple[control] groups differ on some unobserved/omitted dimension. (.hi-slate[Endogeneity])

--

.hi-pink[Instrumental variables] attempts to separate out

- the .hi-slate[exogenous] part of $x$, which gives us unbiased estimates
- the .hi-slate[endogenous] part of $x$, which biases our results

--

If we use only the exogenous (*good*) variation in $x$, then we can avoid selection bias/omitted-variable bias.
---

## Introductory example

*Example:* If we want to estimate the effect of veteran status on earnings,
$$
\begin{align}
  \text{Earnings}_i = \beta_0 + \beta_1 \text{Veteran}_i + u_i \tag{1}
\end{align}
$$

--

We would love to calculate $\color{#e64173}{\text{Earnings}_{1i}} - \color{#6A5ACD}{\text{Earnings}_{0i}}$, but we can't.

--

And OLS will likely be biased for $(1)$ due to selection/omitted-variable bias.

---

## Introductory example

Imagine that we can split veteran status into an exogenous part and an endogenous part...

--

$$
\begin{align}
  \text{Earnings}_i
  &= \beta_0 + \beta_1 \left(\text{Veteran}_i^{\text{Exog.}} + \text{Veteran}_i^{\text{Endog.}}\right) + u_i \\
  &= \beta_0 + \beta_1 \text{Veteran}_i^{\text{Exog.}} + \underbrace{\beta_1 \text{Veteran}_i^{\text{Endog.}} + u_i}_{w_i} \\
  &= \beta_0 + \beta_1 \text{Veteran}_i^{\text{Exog.}} + w_i
\end{align}
$$

--

We could use this exogenous variation in veteran status to consistently estimate $\beta_1$.

--

**Q:** What would exogenous variation in veteran status mean?
---

## Introductory example

**Q:** What would exogenous variation in veteran status mean?

--

**A.sub[1]:** Choices to enlist in the military that are essentially random—or at least uncorrelated with omitted variables and the disturbance.

--

**A.sub[2]:** .hi-orange[No selection bias:]
$$
\begin{align}
  \color{#e64173}{\mathop{Avg}\left(\text{Earnings}_{0i}\mid\text{Veteran}_i = 1\right)} - \color{#6A5ACD}{\mathop{Avg}\left( \text{Earnings}_{0i} \mid \text{Veteran}_i = 0 \right)} = 0
\end{align}
$$

---
name: instruments

## Instruments

**Q:** How do we isolate this *exogenous variation* in our explanatory variable?
--
<br>**A:** Find an instrument (an instrumental variable).

--

**Q:** What's an instrument?
--
<br>**A:** An .hi-pink[instrument] is a variable that is

1. **correlated** with the **explanatory variable** of interest (.hi[relevant]),
2. **uncorrelated** with the **disturbance** (.hi[exogenous]).

---

## Instruments

>**Q:** What's an instrument?
><br>**A:** An .hi-pink[instrument] is a variable that is
>
>1. **correlated** with the **explanatory variable** of interest (.hi[relevant]),
>2. **uncorrelated** with the **disturbance** (.hi[exogenous]).

--

So if we want an instrument $z_i$ for endogenous veteran status in
$$
\begin{align}
  \text{Earnings}_i = \beta_0 + \beta_1 \text{Veteran}_i + u_i
\end{align}
$$

1. .hi[Relevant:] $\mathop{\text{Cov}} \left( \text{Veteran}_i,\, z_i \right) \neq 0$
2. .hi[Exogenous:] $\mathop{\text{Cov}} \left( z_i,\, u_i \right) = 0$
---
name: relevant

## Instruments: Relevance

.hi[Relevance:] We need the instrument to cause a change in (correlate with) our endogenous explanatory variable.

We can actually test this requirement using regression and a *t* test.

--

***Example:*** For the .pink[veteran status], consider three potential instruments:

.pull-left[1\. Social security number<br>.white[blank]]

--

.pull-right[.hi-slate[Probably not relevant]<br>uncorrelated with military service]

--

.pull-left[2\. Physical fitness<br>.white[blank]]

--

.pull-right[.hi-pink[Potentially relevant]<br>service may correlate with fitness]

--

.pull-left[3\. Vietnam War draft]

--

.pull-right[.hi-pink[Relevant]<br>being draw led to service]

---
name: exogenous

## Instruments: Exogeneity

.hi[Exogeneity:] The instrument to be independent of omitted factors that affect our outcome variable—as good as randomly assigned.

$z_i$ must be uncorrelated with our disturbance $u_i$. .hi[Not testable.]

--

***Example:*** For the .pink[veteran status], consider three potential instruments:

.pull-left[1\. Social security number<br>.white[blank]]

--

.pull-right[.hi-pink[Exogenous]<br>Indep. of other factors of service]

--

.pull-left[2\. Physical fitness<br>.white[blank]]

--

.pull-right[.hi-slate[Not exogenous]<br>fitness correlates with many things]

--

.pull-left[3\. Vietnam War draft]

--

.pull-right[.hi-pink[Exogenous]<br>the lottery was random]

---

## Instrumental review

Let's recap...

- Our instrument must be .hi[correlated with our endogenous variable].

- Our instrument must be .hi[uncorrelated with any other variable that affects the outcome].

--

.hi-slate[In other words:]
<br>The instrument only affects our outcome through the endogenous variable.
---

## Back to our example

For .pink[veteran status] we considered three potential instruments:

--

.pull-left[1\. Social security number<br>.white[blank]<br>.white[blank]]

.pull-right[.hi-slate[Not relevant]<br>.hi-pink[Exogenous]<br>.white[blank]]

--

.pull-left[2\. Physical fitness<br>.white[blank]<br>.white[blank]]

.pull-right[.hi-pink[Probably relevant]<br>.hi-slate[Not exogenous]<br>.white[blank]]

--

.pull-left[3\. Vietnam War draft<br>.white[blank]<br>.white[blank]]

.pull-right[.hi-pink[Relevant]<br>.hi-pink[Exogenous]<br>.white[blank]]

--

Thus, only the Vietnam War's draft lottery appears to be a .hi[*valid* instrument].

---
layout: false
class: clear, middle

If we have a *valid* instrument (_e.g._, the draft lottery), how do we use it?
---
layout: true
# Instrumental variables
## Estimation
---
name: iv_estimation

*Recall:* We want to estimate the effect of veteran status on earnings.
$$
\begin{align}
  \color{#FFA500}{\text{Earnings}_i} = \beta_0 + \beta_1 \color{#6A5ACD}{\text{Veteran}_i} + u_i
\end{align}
$$

--

Let's consider two related effects:

--

1. The effect of the .hi-pink[instrument] on the .hi-purple[endogenous variable], _e.g._,
$$
\begin{align}
  \color{#6A5ACD}{\text{Veteran}_i} = \gamma_0 + \gamma_1 \color{#e64173}{\text{Draft}_i} + v_i
\end{align}
$$

--
1. The effect of the .hi-pink[instrument] on the .hi-orange[outcome variable], _e.g._,
$$
\begin{align}
  \color{#FFA500}{\text{Earnings}_i} = \pi_0 + \pi_1 \color{#e64173}{\text{Draft}_i} + w_i
\end{align}
$$
---

*Recall:* We want to estimate the effect of veteran status on earnings.
$$
\begin{align}
  \color{#FFA500}{\text{Earnings}_i} = \beta_0 + \beta_1 \color{#6A5ACD}{\text{Veteran}_i} + u_i
\end{align}
$$
and we know that the draft affected veteran status.

--

.center[
.hi-pink[Draft] ⟶ .hi-purple[Veteran status] ⟶ .hi-orange[Earnings]
]

Using our assumptions on independence and exogeneity:

(Effect of .hi-pink[the draft] on .hi-orange[earnings]) =
<br>  (Effect of .hi-pink[the draft] on .hi-purple[veteran status])×
<br>  (Effect of .hi-purple[veteran status] on .hi-orange[earnings])
---

We just wrote out an expression for the effect of .hi-pink[the draft] on .hi-orange[earnings], _i.e._,

(Effect of .hi-pink[the draft] on .hi-orange[earnings]) =
<br>  (Effect of .hi-pink[the draft] on .hi-purple[veteran status])×
<br>  (Effect of .hi-purple[veteran status] on .hi-orange[earnings])

--

but we want to know the effect of .hi-purple[veteran status] on .hi-orange[earnings].
--
 Rearrange!

--

(Effect of .hi-purple[veteran status] on .hi-orange[earnings]) =
<br>  .top[(Effect of .hi-pink[the draft] on .hi-orange[earnings])]
<br>  .bottom[(Effect of .hi-pink[the draft] on .hi-purple[veteran status])]

--

Our .hi-pink[instrument] consistently estimates both parts of this fraction!
---
layout: true
# Instrumental variables
## Estimation: Bring it all together
---

By estimating two regressions involving our .hi-pink[instrument],

1. The effect of the .hi-pink[instrument] on the .hi-purple[endogenous variable], _e.g._,
$$
\begin{align}
  \color{#6A5ACD}{\text{Veteran}_i} = \gamma_0 + \gamma_1 \color{#e64173}{\text{Draft}_i} + v_i
\end{align}
$$

1. The effect of the .hi-pink[instrument] on the .hi-orange[outcome variable], _e.g._,
$$
\begin{align}
  \color{#FFA500}{\text{Earnings}_i} = \pi_0 + \pi_1 \color{#e64173}{\text{Draft}_i} + w_i
\end{align}
$$

--

we can estimate our desired effect:

--

(Effect of .hi-purple[veteran status] on .hi-orange[earnings]) =
<br>  .top[(Effect of .hi-pink[the draft] on .hi-orange[earnings])]
<br>  .bottom[(Effect of .hi-pink[the draft] on .hi-purple[veteran status])]

---
count: false

By estimating two regressions involving our .hi-pink[instrument],

1. The effect of the .hi-pink[instrument] on the .hi-purple[endogenous variable], _e.g._,
$$
\begin{align}
  \color{#6A5ACD}{\text{Veteran}_i} = \gamma_0 + \gamma_1 \color{#e64173}{\text{Draft}_i} + v_i
\end{align}
$$

1. The effect of the .hi-pink[instrument] on the .hi-orange[outcome variable], _e.g._,
$$
\begin{align}
  \color{#FFA500}{\text{Earnings}_i} = \pi_0 + \pi_1 \color{#e64173}{\text{Draft}_i} + w_i
\end{align}
$$

we can estimate our desired effect:

(Effect of .hi-purple[veteran status] on .hi-orange[earnings]) = $\dfrac{\pi_1}{\gamma_1}$
---
layout: false
class: clear, middle

Let's work an example in .mono[R].
---
layout: true
# Instrumental variables
## Example in .mono[R]
---
name: r_example

Back to our age-old battle to estimate the returns to education.

```{R, wooldridge_data, echo = F}
# Grab desired variables
wage_df <- wage2 %>% transmute(wage, educ, educ_dad = feduc, educ_mom = meduc) %>% na.omit() %>% as_tibble()
# Print to screen
wage_df
```
---

OLS for the returns to education is likely (definitely) biased...

```{R, ols, echo = F}
lm(wage ~ educ, wage_df) %>% tidy()
```

but what if father's or mother's education provide a valid instrument?

--

**Q:** Why/why not?
---
layout: false
class: clear, middle

.mono[Live coding here.]

---
layout: false
# Table of contents

.pull-left[
### Admin
.smallest[

1. [Schedule](#schedule)
1. [Masters program](#masters)
1. [Causality review](#causality_review)
]
]

.pull-right[
### Instrumental variables
.smallest[

1. [Introduction](#intro)
1. [What is an instrument?](#instruments)
  - [Relevant](#relevant)
  - [Exogenous](#exogenous)
1. [IV Estimation](#iv_estimation)
1. [.mono[R] example](#r_example)
]
]
---
exclude: true

```{R, generate pdfs, include = F, eval = T}
system("decktape remark 11_instrumental_variables.html 11_instrumental_variables.pdf --chrome-arg=--allow-file-access-from-files")
```
